#Site Settings
title: This is a test environment for my homepage.
url: https://fanwu-repo-test.github.io
baseurl: ''
description: >
  Test environment.

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-leap-day
